/*
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference,
 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
*/

/*
I did not manage to come up with some actual limit for the list, so I just tested
some arbitrary number which seemed to be 'big enough' and I tried the result which
happen to be correct one;
*/
const generateList = (n = 10000) => {
  let list = [];
  for (let i = 1; i < n - 1; i++) {
    list[i] = (i * (3 * i - 1)) / 2;
  }

  return list;
};

// see isTriangleNumber in problem 42
const isPentagonal = (p) => {
  const n1 = (1 + Math.sqrt(1 + 24 * p)) / 6;
  const n2 = (1 - Math.sqrt(1 + 24 * p)) / 6;

  return (n1 > 0 && n1 % 1 === 0) || (n2 > 0 && n2 % 1 === 0);
};

const problem = (n) => {
  const list = generateList(n);
  let output = [];
  for (let i = 1; i < list.length; i++) {
    const k = list[i];
    for (let j = i; j < list.length; j++) {
      const l = list[j];
      if (isPentagonal(k + l) && isPentagonal(Math.abs(k - l))) {
        output.push([k, l]);
      }
    }
  }

  return output.reduce((_, [k, l]) => Math.min(Math.abs(k - l)), Infinity);
};

module.exports = problem;
