/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms

https://projecteuler.net/problem=2
*/

const fibonacciSum = (a = 0, b = 1, sum = 1, upTo = 4000000) => {
  const next = a + b;
  if (next > upTo) return sum;

  const nextSum = next % 2 === 0 ? sum : sum + next;

  return fibonacciSum(b, next, nextSum, upTo);
};

module.exports = fibonacciSum;
