/*
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
*/

const triangleNumber = (n) => (n * (n + 1)) / 2;

// see problem 42
const isPentagonal = (p) => {
  const n1 = (1 + Math.sqrt(1 + 24 * p)) / 6;
  const n2 = (1 - Math.sqrt(1 + 24 * p)) / 6;

  return (n1 > 0 && n1 % 1 === 0) || (n2 > 0 && n2 % 1 === 0);
};

const isHexagonal = (h) => {
  const n1 = (1 + Math.sqrt(1 + 8 * h)) / 4;
  const n2 = (1 - Math.sqrt(1 + 8 * h)) / 4;

  return (n1 > 0 && n1 % 1 === 0) || (n2 > 0 && n2 % 1 === 0);
};

const problem = (i = 286) => {
  let n;
  while (!isPentagonal(n) || !isHexagonal(n)) {
    n = triangleNumber(i++);
  }
  return n;
};

module.exports = problem;
